#include "xsobel_filter.h" // Generated by HLS
#include "xil_printf.h"

XSobel_filter_top instance;

int main() {
    // Initialize the IP driver
    XSobel_filter_top_Initialize(&instance, 0);

    while(1) {
        // Pseudo-code: Listen for UART byte from ESP32
        // If (UART_data_received) {
        //    int new_threshold = read_uart();
        //    XSobel_filter_top_Set_threshold(&instance, new_threshold);
        // }
    }
}